### ISSUE TITLE
Issues encountered during testing hackathon

### ISSUE THREAD

**Issue by jack4707** [NCBI-Hackathons/MetagenomicAntibioticResistance#15]
I encountered the following problems while testing the pipeline -

* Need to make it explicit in the installation instructions that the code and databases should be downloaded and run inside the docker image 

* Provide links to download locations for the databases needed
* Is refseq bacteria actually needed? I could not find a reference to it in the main.sh script (seemed to jump from step 2 to step 4 between lines 29 and 31, omitting a magicblast against the refseq database

* It is cumbersome to download the databases into the docker image each time they are needed (took around 15 minutes each time). During the initial setup I lost wifi connection, dropping my ssh link and closing the docker instance - upon reopening the image it is reset to a blank state and I had to repeat. 

* The dockerfile needs to include installation of git, samtools and sra-toolkit

* The flags in the usage instructions in the git readme (main.sh -S SRRXXX -o output) do not work, error is 
    * Not Enough Arguments. Please enter sh nastyBugs.sh [SRA Directory] [Host Genome Directory] [Card Database Directory] [Variant Database Directory] [Available Cores] [Output Directory]
    Checking the main.sh script seems to confirm that flags are not implemented

* Need better description of the required database file structure to run, I couldn't get beyond error 
    * Blast Database Error: no alias or index file found for nucleotide database [GRCh37/hg19]
    * there was a fna.gz file in that directory, do I need to index this? - should be explained - I ran out of time here

**Comment by harper357** [comment]
Thanks for testing Jack. Would you mind making separate issues for the problems you encountered? It will make it much easier to make sure they get fixed.

**Comment by stevetsa** [comment]
All issues addressed in the latest version.
https://github.com/stevetsa/MetagenomicAntibioticResistance

**Comment by jack4707** [comment]
I tested Steve's latest version, and the old issues have been addressed well. I encountered a few new problems, so I will close this issue and open some new ones.
